### ISSUE TITLE
Can't the device select a microphone?

### ISSUE THREAD

**Issue by photkey** [osamusg/SpeAnaLED#4]

**Comment by osamusg** [comment]
It's not APP function, but OS(Windows) function.
You can follow this useful video. https://www.youtube.com/watch?v=8KdjSqW1s6U

**Comment by photkey** [comment]
Thank you for your reply. I followed the steps shown in the video, but that's not what I need. I just want to listen to the audio fluctuations of the microphone, not play the microphone sound.
Let me tell you about a real-world use case. I used [SenseVoice](https://github.com/FunAudioLLM/SenseVoice/blob/main/README_ja.md) (a speech-to-text project) to easily create a quick voice input tool. The only thing missing when speaking is a beautiful GUI display like this project

**Comment by osamusg** [comment]
Under Windows OS, "playback device" and "recording device" is completely distinct, you know. And this APP's functions are deeply depends on the BASS.DLL library, so the function supports only "playback" devices.
I can't correspond "recording" device w/o major renovations (from scratch), in other words, it's a completely another software.
The only thing we can do at this time, mic ->(procedure above)-> playback device -> SpeAnaLED(display).
Thank you for your understanding.

**Comment by photkey** [comment]
I understand, thank you for your answer
